version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "srv-sec-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rg6zbakb6okg"
s3_prefix = "srv-sec-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
